### PR TITLE
56-updated home design

### LINKED ISSUE #56: Update home page design

### PR DESCRIPTION
**Pull request by etamiller**

### CODE REVIEW

**Comment by ChanaMar2** [comment]
When I open the branch in my browser, the background pic doesn't extend til the bottom of the page

**Comment by etamiller** [comment]
Ok. Thanks for letting me know. I'll work on that.

**Review by ChanaMar2 — APPROVED** [review]
Now it goes til the bottom!

**Review by Egrosberg — APPROVED** [review]

**Review by elishevarom — CHANGES_REQUESTED** [review]
Same here about using bootstrap

**Review by SerachS — APPROVED** [review]

**Pull request closed without merging**
