### PR TITLE
Added background img files

### LINKED ISSUE #52: upload background images

### PR DESCRIPTION
**Pull request by ChanaMar2**
Added all navy backgrounds to src folder

### CODE REVIEW

**Review by SerachS — APPROVED** [review]

**Comment by SerachS** [comment]
Thank you!!

**Comment by etamiller** [comment]
5/6 of them say 'Unable to render rich display' when viewing the files changed...does that matter or is it just saying that it can't show a "preview" on github?

**Comment by ChanaMar2** [comment]
They show up for me without saying that

**Review by Egrosberg — APPROVED** [review]

**Review by etamiller — APPROVED** [review]
Ok great!

**Pull request merged**
